### ISSUE TITLE
error: duplicate value for resource 'attr/progress' with config ''

### ISSUE THREAD

**Issue by jamilxt** [VaibhavLakhera/Circular-Progress-View#1]
Showing this two error:
error: duplicate value for resource 'attr/progress' with config ''
error: resource previously defined here.

**Comment by VaibhavLakhera** [comment]
Hello @jamilxt 
Thanks for reporting the issue. Seems like there is already an attribute named "progress" in your project which is causing duplicate value error.

Can you provide some information on SDK version and dependencies that you're using which could help in recreating the issue. Otherwise if the problem persists, then i'll push a new release with updated attribute names.

**Comment by jamilxt** [comment]
SDK Version: 28
Migrated to AndroidX


And I've tried enabling mutltidex. Not working. What I've found that -> renaming the attribute will probably fix the issue. 😊

**Comment by VaibhavLakhera** [comment]
Updated attribute names in version 0.1.2

"app:progress" to "app:progressValue"
and
"app:total" to "app:totalValue"

That should fix the issue. Let me know how it goes.

**Comment by jamilxt** [comment]
Working great! 💯 Thanks. ^_^

**Comment by jamilxt** [comment]
Is there any way to set Float Value as Progress and show it with animation?

**Comment by VaibhavLakhera** [comment]
@jamilxt 

It only takes integer for now. So, you have to convert your float to an integer for the progress and total.

**Comment by jamilxt** [comment]
Nope, progress will be in percentage but the inside text will be like - 4.5, 3.9.

**Comment by VaibhavLakhera** [comment]
Yes that is possible. I have to add faction value to the displayed value in case of percentage.

Would you like floating values for normal progress as well?

**Comment by jamilxt** [comment]
Yeah, that will be cool! 
What I am doing is,
I am using RelativeLayout to make the text (4.5) in the center and did hide the real progress value in the center.
